name: 'sonarscanner'
description: 'Install and configure sonar-scanner'
inputs:
  sonar-scanner-version:
    description: 'Version of sonar-scanner'
    required: true
    default: '4.3.0.2102'
  install-dir:
    description: 'Directory for sonar-scanner installation (absolute path without environment variables)'
    required: true
    default: '/home/runner/sonarscanner'
runs:
  using: 'node12'
  main: 'dist/index.js'

