name: 'sonarscanner'
description: 'Install and run sonar-scanner'
inputs:
  sonar-scanner-version:
    description: 'Version of sonar-scanner'
    required: true
    default: '4.2.0.1873'
  run:
    description: 'Whether to run sonar-scanner after installing'
    required: true
    default: 'true'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'

